export const types = {
  SUPER_LIGHT: 'SUPER_LIGHT',
  LIGHT: 'LIGHT',
  MEDIUM: 'MEDIUM',
  HEAVY: 'HEAVY',
  SUPER_HEAVY: 'SUPER_HEAVY',
};

export const shipAmounts = {
  202: { type: types.SUPER_LIGHT },
  203: { type: types.SUPER_LIGHT },
  204: { type: types.SUPER_LIGHT },
  205: { type: types.SUPER_LIGHT },
  206: { type: types.LIGHT },
  207: { type: types.MEDIUM },
  208: { type: types.MEDIUM },
  209: { type: types.LIGHT },
  210: { type: types.SUPER_LIGHT },
  211: { type: types.HEAVY },
  213: { type: types.HEAVY },
  214: { type: types.SUPER_HEAVY },
  215: { type: types.HEAVY },
  216: { type: types.SUPER_HEAVY },
  218: { type: types.SUPER_HEAVY },
  219: { type: types.SUPER_HEAVY },
  220: { type: types.SUPER_HEAVY },
  221: { type: types.SUPER_HEAVY },
  222: { type: types.LIGHT },
  401: { type: types.SUPER_LIGHT },
  402: { type: types.SUPER_LIGHT },
  403: { type: types.LIGHT },
  404: { type: types.MEDIUM },
  405: { type: types.LIGHT },
  406: { type: types.HEAVY },
}